=== son-min-wook/stoup/ex2/newspaper.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="stringtype">
<xs:restriction base="xs:string"/>
</xs:simpleType>

<xs:complexType name="newspapertype">
<xs:sequence>
<xs:element name="article" type="articletype" minOccurs="1" maxOccurs="unbounded"/>
<xs:element name="newspapers" type="stringtype" fixed="Vervet Logic Times"/>
<xs:element name="publisher" type="stringtype" fixed="Vervet Logic Press"/>
<xs:element name="copyright" type="stringtype" fixed="Copyright 1998 Vervet Logic Press"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="articletype">
<xs:sequence>
<xs:element name="headline" type="stringtype"/>
<xs:element name="byline" type="stringtype"/>
<xs:element name="lead" type="stringtype"/>
<xs:element name="body" type="stringtype"/>
<xs:element name="notes" type="stringtype"/>
</xs:sequence>
<xs:attribute name="author" type="stringtype" use="required"/>
<xs:attribute name="editor" type="stringtype" use="optional"/>
<xs:attribute name="date" type="stringtype" use="optional"/>
<xs:attribute name="edition" type="stringtype" use="optional"/>
</xs:complexType>

<xs:element name="newspaper" type="newspapertype"/>
</xs:schema>

=== son-min-wook/stoup/ex2/newspaper.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<newspaper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="newspaper.xsd">
<article author="harry" editor="potter" date="09/11" edition="first">
<headline>bangbang</headline>
<byline>b2b2</byline>
<lead>leeeeead</lead>
<body>sline</body>
<notes>death</notes>
</article>
<newspapers/>
<publisher/>
<copyright/>
</newspaper>
