=== son-min-wook/stoup/ex2/tvschedule.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="stringtype">
<xs:restriction base="xs:string"/>
</xs:simpleType>

<xs:complexType name="titletype">
 <xs:attribute name="rating" type="stringtype" use="optional"/>
 <xs:attribute name="language" type="stringtype" use="optional"/>
</xs:complexType>

<xs:complexType name="programslottype">
<xs:sequence>
 <xs:element name="time" type="stringtype"/>
 <xs:element name="title" type="titletype"/>
 <xs:element name="description" type="stringtype" maxOccurs="1" minOccurs="0"/>
 </xs:sequence>
 <xs:attribute name="vtr" type="stringtype" use="optional"/>
</xs:complexType>

<xs:complexType name="channeltype">
<xs:sequence>
<xs:element name="banner" type="stringtype"/>
<xs:element name="day" type="daytype" minOccurs="1" maxOccurs="unbounded" />
</xs:sequence>
<xs:attribute name="chan" type="stringtype" use="required"/>
</xs:complexType>

<xs:complexType name="daytype">
 <xs:sequence> 
<xs:element name="date" type="stringtype"/>
<xs:choice minOccurs="1" maxOccurs="unbounded">
<xs:element name="holiday" type="stringtype"/>
<xs:element name="programslot" type="programslottype" minOccurs="1" maxOccurs="unbounded"/>
</xs:choice>
</xs:sequence>
</xs:complexType>

<xs:complexType name="tvscheduletype">
 <xs:sequence>
  <xs:element name="channel" type="channeltype" minOccurs="1" maxOccurs="unbounded"/>
 </xs:sequence>
 <xs:attribute name="name" type="stringtype" use="required"/>
</xs:complexType>

<xs:element name="tvschedule" type="tvscheduletype"/>
</xs:schema>

=== son-min-wook/stoup/ex2/tvschedule.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<tvschedule name="ocn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="tvschedule.xsd">
<channel chan="52">
<banner>movie</banner>
<day>
<date>09/13</date>
<holiday>sat</holiday>
</day>
</channel>
<channel chan="53">
<banner>movie1</banner>
<day>
<date>09/14</date>
<programslot vtr="umm">
<time>18:00</time>
<title rating="1" language="eng"></title>
<description>hmm</description>
</programslot>
</day>
</channel>
</tvschedule>
