=== son-min-wook/stoup/ex1/bulletin.dtd
<!ELEMENT BOARD (NAME,(ARTICLE+))>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT ARTICLE (TITLE,MESSAGE,WRITERID,WRITERNAME,(REPLY*))>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT MESSAGE (#PCDATA)>
<!ELEMENT WRITERID (#PCDATA)>
<!ELEMENT WRITERNAME (#PCDATA)>
<!ELEMENT REPLY (MESSAGE,WRITERID,WRITERNAME)>

=== son-min-wook/stoup/web-programming/ex1/bulletin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BOARD SYSTEM "bulletin.dtd">
<BOARD>
<NAME>breaking news</NAME>
  <ARTICLE>
      <TITLE>Soccer</TITLE>
	  <MESSAGE>Korea win</MESSAGE>
	  <WRITERID>201433688</WRITERID>
	  <WRITERNAME>sonminwook</WRITERNAME>
	  <REPLY>
	     <MESSAGE>good</MESSAGE>
		 <WRITERID>1234</WRITERID>
		 <WRITERNAME>no one</WRITERNAME>
	  </REPLY>
  </ARTICLE>
  <ARTICLE>
      <TITLE>Baseball</TITLE>
	  <MESSAGE>Korea lose</MESSAGE>
	  <WRITERID>201433688</WRITERID>
	  <WRITERNAME>sonminwook</WRITERNAME>
	  <REPLY>
	     <MESSAGE>sign....</MESSAGE>
		 <WRITERID>4321</WRITERID>
		 <WRITERNAME>any one</WRITERNAME>
	  </REPLY>
  </ARTICLE>
</BOARD>
